include: package:lint/analysis_options_package.yaml
linter:
  rules:
    avoid_void_async: false
    avoid_function_literals_in_foreach_calls: false
    use_key_in_widget_constructors: false
    avoid_positional_boolean_parameters: false
    use_setters_to_change_properties: false
    avoid_classes_with_only_static_members: false